project:
  type: website
  output-dir: docs

website:
  title: "Timothy Mulderrig"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - presentations.qmd
      - teaching.qmd
      - contact.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    page-layout: full



